# Generated by Django 3.0 on 2020-01-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
    ]
